import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Marta",
      email: "look4meanil@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Hemanth",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Princess Party Supplies",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 130,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Wedding Supplies",
      category: "Adult",
      image: "/images/Product2/Product2.1.jpeg",
      price: 200,
      countInStock: 10,
      rating: 5.0,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Birthday Party Supplies",
      category: "Kids",
      image: "/images/Product3/Product3.1.jpeg",
      price: 150,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Valentines Supplies",
      category: "Adult",
      image: "/images/pic1.png",
      price: 200,
      countInStock: 3,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "School Party Supplies",
      category: "Kids",
      image: "/images/pic1.png",
      price: 150,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
  ],
};
export default data;
