import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Marta",
      email: "look4meanil@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Hemanth",
      email: "user@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Product 1",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 130,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 2",
      category: "Adult",
      image: "/images/Product1/Product1.1.jpeg",
      price: 200,
      countInStock: 10,
      rating: 5.0,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 3",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 150,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 4",
      category: "Adult",
      image: "/images/Product1/Product1.1.jpeg",
      price: 200,
      countInStock: 3,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 5",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 150,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 6",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 150,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 7",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 150,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      name: "Product 8",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 150,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
  ],
};
export default data;
