const data = {
  products: [
    {
      _id: "1",
      name: "Princess Party Supplies",
      category: "Kids",
      image: "/images/Product1/Product1.1.jpeg",
      price: 130,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      _id: "2",
      name: "Wedding Supplies",
      category: "Adult",
      image: "/images/pic1.png",
      price: 200,
      countInStock: 10,
      rating: 5.0,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      _id: "3",
      name: "Birthday Party Supplies",
      category: "Kids",
      image: "/images/pic1.png",
      price: 150,
      countInStock: 0,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      _id: "4",
      name: "Valentines Supplies",
      category: "Adult",
      image: "/images/pic1.png",
      price: 200,
      countInStock: 3,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
    {
      _id: "5",
      name: "School Party Supplies",
      category: "Kids",
      image: "/images/pic1.png",
      price: 150,
      countInStock: 1,
      rating: 4.5,
      numReviews: 10,
      description: "Most selling product",
    },
  ],
};
export default data;
